name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # use the dummy env variable for now
    env:
      DEBUG: "false"
      DATABASE_URL: "postgresql+psycopg2://postgres:ShekhaRpc@29@db:5432/my-db"
      REDIS_URL: "redis://localhost:6379"
      SECRET_KEY: "mynameisshekhar@123"
      access_token_expire_minutes: "15"
      refresh_token_expire_days: "3"
      algo: "HS256"


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest